/* eslint-disable */
/**
 * THIS FILE IS AUTO-GENERATED by `scripts/generate-routes.mjs`.
 * Do not edit by hand. It is gitignored and recreated on dev/build.
 *
 * Config: scripts/routes.config.mjs
 * Regenerate: npm run routes:generate
 */

export const panelNextAllowlist = [
  "/panel/dashboard",
] as const;

export type PanelNextPath = (typeof panelNextAllowlist)[number];

function isPanelNextPath(value: string): value is PanelNextPath {
  return (panelNextAllowlist as readonly string[]).includes(value);
}

/** Honor `next` only when it matches the panel allowlist; else panel default. */
export function resolveNextPath(next: string | null | undefined): string {
  if (next && isPanelNextPath(next)) {
    return next;
  }
  return routes.panel.dashboard();
}

export const routes = {
  auth: {
    login: (opts?: { next?: string }) => {
      if (!opts) return "/";
      const sp = new URLSearchParams();
      if (opts.next != null && opts.next !== "") sp.set("next", opts.next);
      const q = sp.toString();
      return q ? `/?${q}` : "/";
    },
  },
  accessDenied: () => "/access-denied",
  panel: {
    dashboard: () => "/panel/dashboard",
  },
  unauthorized: () => "/unauthorized",
} as const;
